version: '3.4'

services:
  aspnetapp:
    image: myaspnetapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - OTel__Exporter__Otlp__Endpoint=otel-collector:4318  # Configure OTel SDK to send telemetry to the OTel Collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC receiver
      - "14268:14268"  # Jaeger HTTP receiver
    
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest  # Using the contrib image which has more features
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    command: ["--config=/etc/otel-collector-config.yaml"]  # Start collector with the specified config file
    depends_on:
      - jaeger
      - prometheus
